# https://pkg.go.dev/github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen#Configuration
# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

package: main
output: server.gen.go
generate:
  std-http-server: true
  strict-server: true
  embedded-spec: true
  models: true
